name: Create Release on Tag

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Archive Release Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: jar
        path: build/libs/CyberEnte-fabric.jar

  release:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Download Release Artifacts
          uses: actions/download-artifact@v4
          with:
            name: jar
            path: release

        - name: Create Release
          uses: softprops/action-gh-release@v2
          with:
            tag_name: ${{ github.ref_name }}
            name: Release ${{ github.ref_name }}
            draft: false
            prerelease: false
            files: release/CyberEnte-fabric.jar
            body: |
              This is an automatically generated release.

              _Generated by GitHub Actions._
